version: '3'
networks:
  quake-net:

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - database

  database: 
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: quake
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - 5432:5432
    networks:
      - quake-net

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    depends_on:
      - database
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: password
    ports: 
      - 8081:80
    networks:
      - quake-net